# Generated by Django 2.0.13 on 2019-03-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chambers', '0002_auto_20190318_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamber',
            old_name='display_name',
            new_name='chamber',
        ),
    ]
