# Generated by Django 2.0.13 on 2019-03-19 18:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambers', '0003_auto_20190319_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamber',
            name='automod',
        ),
        migrations.AddField(
            model_name='chamber',
            name='automod_a',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chamber',
            name='automod_b',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chamber',
            name='automod_c',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chamber',
            name='automod_d',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chamber',
            name='automod_e',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chamber',
            name='severity_a',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3),
        ),
        migrations.AddField(
            model_name='chamber',
            name='severity_b',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3),
        ),
        migrations.AddField(
            model_name='chamber',
            name='severity_c',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3),
        ),
        migrations.AddField(
            model_name='chamber',
            name='severity_d',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3),
        ),
        migrations.AddField(
            model_name='chamber',
            name='severity_e',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3),
        ),
    ]
