# Generated by Django 2.0.13 on 2019-03-19 22:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambers', '0004_auto_20190319_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='chamber',
            name='min_comment_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='chamber',
            name='min_thread_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
    ]
