# Generated by Django 2.0.13 on 2019-03-20 15:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambers', '0005_auto_20190319_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='automod_can_fine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chamber',
            name='max_fine',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4),
        ),
    ]
