# Generated by Django 2.0.13 on 2019-03-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20190318_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='chamber',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
