# Generated by Django 2.0.13 on 2019-03-19 22:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_link_chamber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=8),
        ),
    ]
