# Generated by Django 2.0.13 on 2019-03-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_profile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='motto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_down_given',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_uo_given',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_users_paid',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
